---
# pulling from git would be better here
- name: synchronize app files
  synchronize: src=../../../../ dest={{ app_directory }}

- name: bundle install
  command: bash -lc "cd {{ app_directory }} && bundle install --without development test"

- name: run migrations
  command: bash -lc "cd {{ app_directory}} bundle exec rake db:migrate"

- name: get puma pid id
  command: cat {{ app_directory }}tmp/puma/pid
  register: pid_id

- name: restart puma
  command: kill -s SIGUSR2 {{ pid_id.stdout }}
  register: result
  ignore_errors: True
  notify: restart nginx

- name: start puma
  command: bash -lc "cd {{ app_directory }} && puma"
  when: result|failed
  notify: restart nginx