development:
  adapter: postgresql
  database: mybema_development
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: mybema_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mybema_production
  username: deploy
  pool: 25
  timeout: 12000