development:
  secret_key_base: f32e5eb9e7c2d0527205f8d343e6a2f60c3359f7c26d2feb5cb410a29634ad586d0e28b8bfc20c70b292ca4b7f4c20fdf3e64fb16a931e59cb9cd082c694ada1
  amazon_bucket: <%= ENV["AMAZON_BUCKET"] %>
  amazon_access_key_id: <%= ENV["AMAZON_ACCESS_KEY_ID"] %>
  amazon_secret_access_key: <%= ENV["AMAZON_ACCESS_KEY"] %>

test:
  secret_key_base: f32e5eb9e7c2d0527205f8d343e6a2f60c3359f7c26d2feb5cb410a29634ad586d0e28b8bfc20c70b292ca4b7f4c20fdf3e64fb16a931e59cb9cd082c694ada1

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  amazon_bucket: <%= ENV["AMAZON_BUCKET"] %>
  amazon_access_key_id: <%= ENV["AMAZON_ACCESS_KEY_ID"] %>
  amazon_secret_access_key: <%= ENV["AMAZON_ACCESS_KEY"] %>