# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e4ae81451fbf29392abfbb2f29d02094f155fa8d4be2224f9e46d6ff27d65e105473de46d3d4624026eb2e3386c8cbd7aa41054a1572fb0f9289e65fba00fc5

test:
  secret_key_base: f14d6be4009f59f046c10de69c2ea9f14405bea83997dc22cb169469c9207a291a20b9d38a88dc143ccd8d00c076b5b68df07936b4d1bfdb74c4d51ec1b89615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
